# Generated by Django 5.2.11 on 2026-03-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_options_lesson_is_free_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Đã xuất bản'),
        ),
    ]
