# Generated by Django 5.2.11 on 2026-03-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lesson_video_lesson_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_file',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Dán link YouTube (watch, youtu.be, embed đều được)', max_length=500, null=True),
        ),
    ]
