# Generated by Django 5.1.1 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slide_url',
            field=models.URLField(blank=True, help_text='Dan link slide (Canva, Google Slides, PDF online...)', max_length=500, null=True),
        ),
    ]
