# Generated by Django 5.1.1 on 2026-04-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_slide_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slide_file',
            field=models.FileField(blank=True, help_text='Tải file slide .ppt hoặc .pptx từ máy lên', null=True, upload_to='lessons/slides/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slide_url',
            field=models.URLField(blank=True, help_text='Dùng cho link slide cũ nếu chưa upload file', max_length=500, null=True),
        ),
    ]
