# Generated by Django 5.2.11 on 2026-03-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_teacher'),
        ('courses', '0011_alter_enrollment_course'),
    ]

    operations = [
    ]
