# Generated by Django 5.2.11 on 2026-03-25 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_merge_20260325_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizattempt',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquizattempt',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
