# Generated by Django 5.2.11 on 2026-03-25 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_userquizattempt_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquizattempt',
            options={},
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='created',
        ),
        migrations.AlterField(
            model_name='userquizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.quiz'),
        ),
        migrations.AlterField(
            model_name='userquizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
